include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**

formatter:
  page_width: 120

linter:
  rules:
    - directives_ordering
    - prefer_single_quotes
    - prefer_final_locals
    - unawaited_futures
